### ISSUE TITLE
Create Sign up Page

### ISSUE THREAD

**Issue by brenmeyer2245** [nicebreakers/nicebreakers#14]
It should...
...allow someone to decide if they are signing up as a LEADER or a PARTICIPANT
........todo--make leaders pay?  Can be an option for now?
...require them to enter an email
...require them to enter a first name / last name
...have a placeholder for image uploading component (see #29)

**Comment by pckilgore** [comment]
OK to ignore google auth for now???

**Comment by pckilgore** [comment]
Updated description.

**Comment by brenmeyer2245** [comment]
I think okay to ignore oauth
