### ISSUE TITLE
Archiving this project

### ISSUE THREAD

**Issue by pckilgore** [nicebreakers/nicebreakers#296]
Hi @kevslim @brenmeyer2245 !

Does anyone mind if we archive this project?  Mostly I'm tired of github sending me emails about security holes and I don't really talk about this project at all in interviews and such.

See: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/archiving-a-github-repository

Thanks guys!

**Comment by kevslim** [comment]
@pckilgore 
I don't mind archiving the project
