### ISSUE TITLE
Write PUT route for interactions

### ISSUE THREAD

**Issue by pckilgore** [nicebreakers/nicebreakers#69]
It should...
...accept a userId from the frontend.
...accept an interactionId from the frontend

It should update the input for that user based on the PUT data for that Interaction.

I'm thinking
`/api/me/interactions/:interactionId`
```
{
  userId: X,
  data: 'Some long ass string'
}
```

**Comment by kevslim** [comment]
Closed into #130

**Comment by brenmeyer2245** [comment]
Taking over
